stages:
  - stage1
  - stage2
  - stage3

image: node:alpine
  i

build:
  stage: stage1
  script:
    - cd auth
    - yarn install
    - yarn build

test:
  stage: stage2
  script:
    - cd auth
    - yarn install
    - yarn test



