stages:
  - stage1
  - stage2
  - stage3

image: node:alpine

build:
  stage: stage1
  script:
    - cd auth
    - yarn install
    - yarn build

test:
  stage: stage2
  script:
    - cd auth
    - yarn install
    - yarn test


    # The name of the job
deploy:
  # The image to be used as the base for this job
  image:
    name: gcr.io/k8s-skaffold/skaffold:v1.15.0
  stage: stage3
  retry: 2
  script:
    # Logging in to our gcp account using the service account key (specified in GITLAB variables)
    - echo "$GCP_DEV_SERVICE_KEY" | base64 -d > gcloud-service-key.json
    - gcloud auth activate-service-account --key-file gcloud-service-key.json
    # Specifying the project, zone, cluster to deploy our application in.
    - gcloud config set project $PROJECT_DEV_NAME
    - gcloud config set compute/zone $PROJECT_DEV_REGION
    - gcloud container clusters get-credentials $CLUSTER_DEV_NAME
    - kubectl config get-contexts
    - yarn build
    # Pass in all the environment variables to be passed to skaffold during build and deployment with all the args as documented in https://skaffold.dev/docs/references/cli/ (in our case our cluster context, env vars, namespace and some labels)
    - skaffold run
  only:
    # Run this only for changes in the main branch
    refs:
      - main
